---
title: "R Notebook for PCA nad Hierarchical Clustering"
output: html_notebook
---

# Principal component analysis in R

## Load and display the data
```{r}
data("iris")
head(iris)
```

## Perform PCA on the iris dataset
```{r}
pca_result <- prcomp(iris[, -5], scale. = TRUE)

summary(pca_result)
```

## Plot the PCA scores
```{r echo=F}
library(ggplot2)

pca_scores <- as.data.frame(pca_result$x)
ggplot(pca_scores, 
       aes(PC1, PC2, color = iris$Species)) +
  geom_point(size = 3) +
  ggtitle("PCA Scatterplot (PC1 vs PC2)") +
  xlab(
    paste("PC1 (", 
    round(
    summary(pca_result)$importance[2,1] * 100, 1),
    "% variance)")) +
  ylab(
    paste("PC2 (",
    round(
    summary(pca_result)$importance[2,2] * 100, 1),
    "% variance)")) +
  theme_minimal()
```

## Calculate explained variance
```{r echo=T, fig.show="hide"}

eigenvalues <- pca_result$sdev^2
explained_variance <- eigenvalues / sum(eigenvalues)
cumulative_variance <- cumsum(explained_variance)

# Plot explained variance
explained_variance_df <- data.frame(
  PC = factor(paste0("PC", 1:4), levels = paste0("PC", 1:4)),
  Proportion = explained_variance
)

ggplot(explained_variance_df, aes(x = PC, y = Proportion)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  ggtitle("Proportion of Variance Explained") +
  xlab("Principal Component") +
  ylab("Proportion of Variance") +
  theme_minimal()
```


```{r echo=T, , fig.show="hide"}
## Scree plot showing cumulative variance explained
cumulative_variance_df <-
  data.frame(
    PC = 1:4,
    CumulativeVariance = cumulative_variance
)

ggplot(cumulative_variance_df, 
       aes(x = PC,
           y = CumulativeVariance)) +
  geom_line(group = 1, color = "steelblue") +
  geom_point(size = 3, color = "steelblue") +
  ggtitle("Cumulative Variance Explained") +
  xlab("Principal Component") +
  ylab("Cumulative Variance") +
  scale_y_continuous(limits = c(0, 1)) +
  theme_minimal()
```

# Hierarchical Clustering in R


```{r}
## Load and display the data
data("iris")
head(iris)
```


```{r fig.width=20, fig.height=5}
## Calculate the distance matrix and perform hierarchical clustering
distance_matrix <- dist(iris[, -5])
hclust_result <- hclust(distance_matrix, method = "complete")

# Plot the dendrogram
plot(hclust_result, labels = iris$Species, main = "Dendrogram of Iris Dataset")
```

```{r echo=F, fig.width=3, fig.height=3}
library(dplyr)
## Heatmap using hierarchical clustering
library(pheatmap)
annotation_colors <- list(
  Species = c(setosa = "red",
              versicolor = "blue",
              virginica = "green")
)
# Perform hierarchical clustering
pheatmap(as.matrix(iris[, -5]),
         clustering_distance_rows = "euclidean",
         annotation_colors = annotation_colors,
         treeheight_col = 10,
         treeheight_row = 20,
         clustering_method = "complete", fontsize = 6,
         annotation_col = iris["Species"]) 
```

```{r}
## Cut the dendrogram to obtain clusters
cutree(hclust_result, k = 3)
# make a list of of vectors containing the elements of iris from of each cluster using cutree
# with k=3
#clustered_data <- split(iris, cutree(hclust_result, k =3))
```

```{r fig.width=10, fig.height=4}
## Visualizing clusters
plot(hclust_result)
rect.hclust(hclust_result, k = 5, border = 1:4)



```

